services:
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/kukymbr/goose-docker:latest
    restart: no
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
    volumes:
      - ./migrations:/migrations

  app:
    image: app
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.app
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
